name: Publish Package to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      # ---------------- CHECKOUT ---------------- #
      - name: Checkout Repo
        uses: actions/checkout@v4

      # ---------------- PYTHON ---------------- #
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ---------------- RUST ---------------- #
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # ---------------- INSTALL MATURIN ---------------- #
      - name: Install maturin
        run: pip install maturin

      # ---------------- BUILD PACKAGE ---------------- #
      - name: Build package
        run: maturin build --release -i python3.11

      # ---------------- PUBLISH ---------------- #
      - name: Publish to PyPI
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: maturin publish --no-sdist -i python3.11